readme updated

diff --git a/.github/workflows/aws.yaml b/.github/workflows/aws.yaml
--- a/.github/workflows/aws.yaml
+++ b/.github/workflows/aws.yaml
@@ -1,79 +1,79 @@
-name: Deploy Application Docker Image to EC2 instance
+# name: Deploy Application Docker Image to EC2 instance
 
-on:
-  push:
-    branches:
-      - main
+# on:
+#   push:
+#     branches:
+#       - main
 
-jobs:
-  Continuous-Integration:
-    runs-on: ubuntu-latest
+# jobs:
+#   Continuous-Integration:
+#     runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v3
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
+#       - name: Configure AWS credentials
+#         uses: aws-actions/configure-aws-credentials@v2
+#         with:
+#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#           aws-region: us-east-1
 
-      - name: Login to Amazon ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v1
+#       - name: Login to Amazon ECR
+#         id: login-ecr
+#         uses: aws-actions/amazon-ecr-login@v1
 
-      - name: Build, tag, and push image to Amazon ECR
-        id: build-image
-        env:
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
-          IMAGE_TAG: latest
-        run: |
-          if [ -z "$ECR_REPOSITORY" ]; then
-            echo "::error::The 'ECR_REPO' secret is missing or empty. Please ensure it is defined in your repository secrets."
-            exit 1
-          fi
-          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
-          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
-          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
+#       - name: Build, tag, and push image to Amazon ECR
+#         id: build-image
+#         env:
+#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+#           ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
+#           IMAGE_TAG: latest
+#         run: |
+#           if [ -z "$ECR_REPOSITORY" ]; then
+#             echo "::error::The 'ECR_REPO' secret is missing or empty. Please ensure it is defined in your repository secrets."
+#             exit 1
+#           fi
+#           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
+#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+#           echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
 
-  Continuous-Deployment:
-    needs: Continuous-Integration
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+#   Continuous-Deployment:
+#     needs: Continuous-Integration
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v3
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
+#       - name: Configure AWS credentials
+#         uses: aws-actions/configure-aws-credentials@v2
+#         with:
+#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#           aws-region: us-east-1
 
-      - name: Login to Amazon ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v1
+#       - name: Login to Amazon ECR
+#         id: login-ecr
+#         uses: aws-actions/amazon-ecr-login@v1
 
-      - name: Run Docker Image on EC2
-        env:
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
-        run: |
-          if [ -z "$ECR_REPOSITORY" ]; then
-             echo "::error::The 'ECR_REPO' secret is missing or empty in CD job."
-             exit 1
-          fi
-          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest
-          docker stop app || true
-          docker rm app || true
-          docker run -d \
-            --name app \
-            -p 5000:5000 \
-            -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
-            -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
-            -e AWS_DEFAULT_REGION="us-east-1" \
-            -e MONGODB_URL="${{ secrets.MONGODB_URL }}" \
-            $ECR_REGISTRY/$ECR_REPOSITORY:latest
+#       - name: Run Docker Image on EC2
+#         env:
+#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+#           ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
+#         run: |
+#           if [ -z "$ECR_REPOSITORY" ]; then
+#              echo "::error::The 'ECR_REPO' secret is missing or empty in CD job."
+#              exit 1
+#           fi
+#           docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest
+#           docker stop app || true
+#           docker rm app || true
+#           docker run -d \
+#             --name app \
+#             -p 5000:5000 \
+#             -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
+#             -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
+#             -e AWS_DEFAULT_REGION="us-east-1" \
+#             -e MONGODB_URL="${{ secrets.MONGODB_URL }}" \
+#             $ECR_REGISTRY/$ECR_REPOSITORY:latest
